### PR TITLE
Add domain in yes/no/slow telemetry calls.

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by wisniewskit** [comment]
Let's wait for Tim's feedback before enabling this. Note also that we'll have to bump the version number up in the manifest.json file while we're at it.

**Comment by tdsmith** [comment]
This is how we [described the collection](https://docs.google.com/document/d/1U4yIu4bktf3lTP6AIAgEuUCzU-z9yc6eg9AOGc12olE/edit#heading=h.6e7748ypotw) for the data review.

tl;dr: The response to the yes/no/slow prompt for the v2 UI only should report the hostname of the website the user is on, unless the user cancels. I think that's the only place we want to add new reporting. We should only report the hostname, not the full URL, unless the user files a report, because full URLs can be more sensitive; we should only collect full URLs through the webcompat-report flow.

We _could_ collect eTLD+1 instead of the full hostname, but I don't think that's important; I can sanitize that on the back end and we're not likely to find cat 4 data embedded in a hostname.

I'm not sure about whether we want to collect hostnames for self-reports; I think I assert the answer is yes, since that's clearly an opt-in decision by the user.

**Comment by wisniewskit** [comment]
This should work fine, but again, I'd recommend also editing manifest.json and bumping the version up to the next minor version (2.0.5) while we're at it.

**Comment by johngian** [comment]
@wisniewskit updated the PR with the version bump

**Pull request merged**
